### ISSUE TITLE
Can also use keyboard to type

### ISSUE THREAD

**Issue by sidling1** [boradesanket13/Numericon#104]

**Comment by Vaibhavpandey1709** [comment]
I want to contribute in this issue

**Comment by pranavjainjs** [comment]
I want to contribute to this issue. Please assign this issue to me.

**Comment by tvermaashutosh** [comment]
Please assign this issue to me sir. I want to contribute to it.

**Comment by boradesanket13** [comment]
@sidling1 Go for it!

**Comment by Gaurav945572** [comment]
Please assign this issue to me
