### ISSUE TITLE
Add a sin, cos, tan operation

### ISSUE THREAD

**Issue by ghost** [boradesanket13/Numericon#107]
I would like to add more operations to the calculator

**Comment by ghost** [comment]
@boradesanket13 please assign this task to me

**Comment by Vaibhavpandey1709** [comment]
I want to participate in this issue.

**Comment by ankushj0801** [comment]
please assign it to me.

**Comment by boradesanket13** [comment]
@itz-deepak Go for it!

**Comment by Gaurav945572** [comment]
Assign this issue to me

**Comment by ghost** [comment]
@Gaurav945572 it is assigned to me and I am working on it

**Comment by boradesanket13** [comment]
@itz-deepak any update on it. If you have any doubt please let us know here!

**Comment by Ghasty003** [comment]
> @itz-deepak any update on it. If you have any doubt please let us know here!

You may assign this issue to me. I'd love to work on it.
