### ISSUE TITLE
adding more operations buttons like x^2 , e^x , log x 

### ISSUE THREAD

**Issue by Yashs-7** [boradesanket13/Numericon#109]
i would like to work on this kindly assign this to me.

**Comment by Yashs-7** [comment]
<img width="1020" alt="Screenshot 2022-12-05 at 1 19 12 PM" src="https://user-images.githubusercontent.com/108972544/205582349-77d9db27-a80d-42fa-922e-e1f603d4b838.png">
attaching a screenshot of how it would look. do suggest any changes if any @boradesanket13

**Comment by tvermaashutosh** [comment]
I am interested in working on this project sir. Please assign this task to me. 🙏

**Comment by 1ananya3** [comment]
I want to work on this issue. I have solved this type of issue before . I know how to solve . Please assign it to me.

**Comment by boradesanket13** [comment]
@thevermaashutosh @1ananya3 Issues are assigned on FCFS basis.

**Comment by boradesanket13** [comment]
Go ahead! Maken PR🚀 @Yashs-7

**Comment by Yashs-7** [comment]
thanks for the opportunity @boradesanket13 , i have sent the PR with the proposed changes, do look 😁🙏

**Comment by boradesanket13** [comment]
🚀
