### ISSUE TITLE
Add input from keyboard

### ISSUE THREAD

**Issue by sshsrn** [boradesanket13/Numericon#114]
I saw the website and noticed that the only way to give input is to click on the numbers, but on usual calculators, we can also give input by directly typing on the keyboard.

### Planned features:
* Map keyboard keys with the inputs.

**Comment by sshsrn** [comment]
@boradesanket13 Kindly assign me this issue for CodePeak!

**Comment by tvermaashutosh** [comment]
@boradesanket13 Please assign this issue to me as I'm eager to work on it.

**Comment by boradesanket13** [comment]
> @boradesanket13 Please assign this issue to me as I'm eager to work on it.

Thanks for your interest!

We're assigning issues on a first come first serve basis. If @SSHSRN  isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another CODEPEAK issue [here](https://github.com/Sanket1308?tab=repositories).
