### ISSUE TITLE
Improve n! (For n = 0)

### ISSUE THREAD

**Issue by vamsikrishnarh7** [boradesanket13/Numericon#115]
It is showing 0! = 0
Make it 1

**Comment by EmberTSeal** [comment]
Please assign me this issue, I'm eager to work on it!

**Comment by Gaurav945572** [comment]
Please assign me this issue

**Comment by banerjee-sarnab** [comment]
You can assign me this issue, I would like to work on it.

**Comment by boradesanket13** [comment]
@EmberTSeal Go ahead! Contribute well🚀

@banerjee-sarnab and @Gaurav945572 , thanks for your interest!
We're assigning issues on a first come first serve basis. If @EmberTSeal isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another CODEPEAK issue [here](https://github.com/boradesanket13?tab=repositories).
