### ISSUE TITLE
Improve UI 

### ISSUE THREAD

**Issue by Yogeshlodhi** [boradesanket13/Numericon#120]
The Colors and the effects on the Calculator should be made better, right now it seems to be a toy kind of thing Also the operator keys there are not looking so great.

**Comment by nandita27iitp** [comment]
Can I work on this issue?

**Comment by boradesanket13** [comment]
#121

**Comment by boradesanket13** [comment]
@Yogeshlodhi , I have awarded the points for creating this issue. Thank you.

@nandita27iitp #121 Do check this issue
