### ISSUE TITLE
Create  Neumorphism UI for calculator 

### ISSUE THREAD

**Issue by Tushar98644** [boradesanket13/Numericon#121]

**Comment by Tushar98644** [comment]
@boradesanket13 I would like to implement it...

**Comment by nandita27iitp** [comment]
Can I work on it?

**Comment by boradesanket13** [comment]
@nandita27iitp thanks for your interest!

We're assigning issues on a first come first serve basis. If @Tushar98644  isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another codepeak issue [here](https://github.com/boradesanket13?tab=repositories).
