### ISSUE TITLE
+/- button is not working in the calculator.

### ISSUE THREAD

**Issue by banerjee-sarnab** [boradesanket13/Numericon#125]
The +/- button is not working. Like if I press 5 and then press the +/- button then it should display -(5) and so on.

**Comment by flukestar123** [comment]
please assign me this issue.

**Comment by GandharveSolanki** [comment]
please assign me this issue .

**Comment by boradesanket13** [comment]
@banerjee-sarnab you want to work on it?

**Comment by therealbenpai** [comment]
readme states that it doesn't support negative numbers?

**Comment by therealbenpai** [comment]
i can work on it too if needed
