### ISSUE TITLE
Add a appropriate image in background

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/Numericon#2]

**Comment by JatinSingh08** [comment]
Hey @Sanket1308 , please assign this to me and please describe about this.

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀

**Comment by JatinSingh08** [comment]
@Sanket1308 Please tell me how's it looking....
![calcigithub](https://user-images.githubusercontent.com/97881261/193454735-d7b15688-5455-41f2-b611-0dfda3fd3e2a.png)

**Comment by JatinSingh08** [comment]
Can I send a PR now ?

**Comment by boradesanket13** [comment]
Use this:
![pexels-johannes-plenio-1103970](https://user-images.githubusercontent.com/79108273/193455668-a92224f3-358b-4293-abad-7ea568a831a8.jpg)

**Comment by JatinSingh08** [comment]
Please review this...

![calcigithub2](https://user-images.githubusercontent.com/97881261/193455879-b3071820-d7d3-427b-994b-34ea25ee9a6b.png)

**Comment by JatinSingh08** [comment]
Is it ok now?



![2022-10-02 (2)](https://user-images.githubusercontent.com/97881261/193457722-387c4ebb-2b73-46de-b0cc-e998a38deefd.png)

**Comment by boradesanket13** [comment]
Yes!

**Comment by JatinSingh08** [comment]
I've sent the pull request.

**Comment by JatinSingh08** [comment]
@Sanket1308 Have merge my PR ? or closed it.

**Comment by boradesanket13** [comment]
@JatinSingh08 It had issues. Check improvement message

**Comment by boradesanket13** [comment]
Completed!
