### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/Numericon#25]

**Comment by Chavda-Mitul** [comment]
assign this to me

**Comment by AdarshCoder397** [comment]
Hey @Sanket1308 , can you assign this to me?

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀

**Comment by AdarshCoder397** [comment]
> Go ahead! Contribute wellrocket
Thanks!

**Comment by AdarshCoder397** [comment]
Hey @Sanket1308 ,  I have made a pull request kindly review and merge it!!!

**Comment by AdarshCoder397** [comment]
Hey @Sanket1308 , I think you might have missed to give me the hacktoberfest-accepted tag!

**Comment by Akshay-21** [comment]
Hey Hi, @Sanket1308, can you assign this to me, so need to update CONTRIBUTING.md to make easier and well documented for contributors.

**Comment by boradesanket13** [comment]
@Akshay-21, thanks for your interest! Happy hacking!🚀

**Comment by Akshay-21** [comment]
Hey Hi @Sanket1308, Thanks for assigning this.

**Comment by sahil-rathi** [comment]
Hey @Sanket1308 can you please assign this to me

**Comment by Akshay-21** [comment]
> @Akshay-21, thanks for your interest! Happy hacking!🚀

Hey Hi @Sanket1308, i have updated CONTRIBUTING.md and also created PR.
pls kindly check this and merge it.

Thank You!

**Comment by boradesanket13** [comment]
> Hey @Sanket1308 can you please assign this to me

Go ahead!

**Comment by sahil-rathi** [comment]
> 
@Sanket1308 
As I can see @Akshay-21 already updated the contributing.md I am unassigning this issue.
But I have made another PR #81 , kindly check that and merge it. Thank you
