### ISSUE TITLE
[CSS] Improve UI

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/Numericon#3]
- Change colors

**Comment by Skysparko** [comment]
hey, @Sanket1308 can I work on it?

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀

**Comment by nomandhoni-cs** [comment]
@Skysparko try to add media query to make responsive in all device

**Comment by Skysparko** [comment]
ok let me add it now @nomandhoni-cs

**Comment by sahilsharma029** [comment]
Hello! can I work on this issue?

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀

**Comment by vaibhav-1508** [comment]
@Sanket1308 I would like to add themes and a toggle button for switching between the themes, can you please assign me this issue?

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀
