### ISSUE TITLE
Change Calculator color

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/Numericon#30]
Change Calculator color
-  It's to dark; need a lighter tone which suits with background image

**Comment by Gur-jot** [comment]
Please Assign this issue to me

**Comment by FreemRL** [comment]
Hey I have changed the background color of the calculator and added the new hex value to [README.md](https://github.com/Sanket1308/Simple-Calculator/blob/main/README.md). The PR is #34

**Comment by boradesanket13** [comment]
We don't want to change button colors here!

**Comment by jyotika6221** [comment]
Hey, please assign me this issue.

**Comment by jyotika6221** [comment]
hey any update.

**Comment by jyotika6221** [comment]
hey, whenever i change the calculator color, the color of few buttons also
changes as if they are linked, is that an issue? if yes, what do i do and
if not i have changed color so please accept the pull request. Thank you.

**Comment by boradesanket13** [comment]
We want the UI to look more authentic and more simple. Start with changing the background image to something less funky.
