### ISSUE TITLE
Fix mobile version

### ISSUE THREAD

**Issue by LaLiLuLeLoPS** [boradesanket13/Numericon#36]
I see the calculator is not working well for mobile version.

Could you assign this fix to me?

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀

**Comment by LaLiLuLeLoPS** [comment]
Hey @Sanket1308 I see you did not merge this PR, was there an issue?

**Comment by boradesanket13** [comment]
Had merge conflicts. Send again

**Comment by LaLiLuLeLoPS** [comment]
Hey @Sanket1308 sent the branch again. no conflicts this time
