### ISSUE TITLE
Website not responsive

### ISSUE THREAD

**Issue by LaLiLuLeLoPS** [boradesanket13/Numericon#39]
The website  currently has static measures and as a result only works for desktop site and scales poorly to irregular views and mobile and tablet views.

I would like to convert to dynamic measures or scaling properties wherever possible so that it scales consistently

**Comment by Skysparko** [comment]
can I work on this issue? @Sanket1308

**Comment by LaLiLuLeLoPS** [comment]
@Skysparko Hey, I'm working on this one buddy :)

**Comment by Skysparko** [comment]
@LaLiLuLeLoPS i already did it

**Comment by LaLiLuLeLoPS** [comment]
@Skysparko Hey buddy, I don't see a PR for your work. I have already sent a PR in for review with my work however.

It generally is considered a bad practice to take an issue someone else is working on.

If you would like, I can help you find some other changes you can work on. Ping me and I'll be glad to help you buddy :)

**Comment by LaLiLuLeLoPS** [comment]
@Sanket1308 I have pushed the PR for this issue. If there is any issue do let me know and I'll fix it or else you can merge it
