### ISSUE TITLE
[Fix] Show output on screen

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/Numericon#5]
- When user types something, it should be visible on the calculator screen

**Comment by tanmay-S12** [comment]
please consider assigning this issue to me.Thank you!

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀

**Comment by nomandhoni-cs** [comment]
@Sanket1308 Issue fixed and output is now showing screen. Merge pull request please
