### ISSUE TITLE
[HTML] Add website title 

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/Numericon#7]
Add website title above calculator as 'Simple Calculator'

**Comment by aryan-errs** [comment]
Pls assign me this

**Comment by shivamnarkar47** [comment]
Hey @Sanket1308 I would like to work on this, Can you assigned it to me :+1: ?

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀

**Comment by Revathi-80** [comment]
Hey @Sanket1308 Can you assign this to me ? I would like to work on this

**Comment by Anandbrewery** [comment]
Hey I am interested to work on this, Can you assign it to me

**Comment by boradesanket13** [comment]
These are assigned for now. Find more issues here:

https://github.com/Sanket1308/Weather-App/
https://github.com/Sanket1308/javascript-quote-generator
https://github.com/Sanket1308/login-page
https://github.com/Sanket1308/Simple-Calculator

**Comment by boradesanket13** [comment]
@Anandbrewery @Revathi-80 @Anandbrewery Fix the position of title

**Comment by Revathi-80** [comment]
@Sanket1308 done

**Comment by Anandbrewery** [comment]
@Sanket1308  have added title for simple calculator
