### ISSUE TITLE
[Enhancement] Pointer Cursor at dark/light mode switch

### ISSUE THREAD

**Issue by incognion** [boradesanket13/Numericon#71]
**Currently, if we move our cursor to dark/light mode switch then it remains default arrow cursor. Here it should be Pointer Cursor, Otherwise switch looks like just a static image. Making it pointer cursor here would enhance user experience.**

- Please assign it to me under Hacktoberfest 2022. Thank you.

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀
