### ISSUE TITLE
Change background images of calculator

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/Numericon#74]
Change background images of calculator
- Add more authentic images (Must look professional!)
- Choose Black image for Dark mode and White for Normal mode. (Different shades of Grey)
- Changes calculator color according to the images color.

**Comment by SatyajeetShinde** [comment]
I want to work on this issue . Can you assign me the task ?

**Comment by jyotika6221** [comment]
Hey please assign assign me this issue.

**Comment by JatinSingh08** [comment]
Hey @Sanket1308 , You merged my pr for background image change. Can you accept that as a mantainer so that my first PR can get accepted for hacktoberfest.

**Comment by Agrimaagrawal** [comment]
I want to work on this issue ,please assign it to me

**Comment by palak100** [comment]
you can assign this to me. I have made web base projects .

**Comment by boradesanket13** [comment]
Thanks for your interest to work on this issue everyone!🚀

We're assigning issues on a first come first serve basis. If @SatyajeetShinde  isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue [here](https://github.com/Sanket1308?tab=repositories).
