### ISSUE TITLE
Animated text!

### ISSUE THREAD

**Issue by shivanidotcom** [boradesanket13/Numericon#78]
Adding animations to the "Simple Calculator".

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀

**Comment by shivanidotcom** [comment]
Yea sure will work on it!

**Comment by shivanidotcom** [comment]
I have Made a PR which solves the issue Animated Text please accept my PR

**Comment by shivanidotcom** [comment]
[image: image.png]
All checks have passed!
