### ISSUE TITLE
[Enhancement] Add a header

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/Numericon#80]
Add a header with logo, 'simple calculator' text, dark mode button, mute button on it

**Comment by jpacsai** [comment]
hi, I would like to work on this issue, please assign it to me :)

**Comment by coderSuren** [comment]
@Sanket1308 Hi I would like to work on this issue, please assign it to me

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀
