### ISSUE TITLE
modify footer

### ISSUE THREAD

**Issue by Gunjanrathore8178** [boradesanket13/Numericon#88]
I can modify footer. pls assign this project to me

**Comment by boradesanket13** [comment]
Specify changes before starting to code

**Comment by Gunjanrathore8178** [comment]
1)Will show steps of instructions
2)techniques used
3)for any query button
4)for contacting and login signup forms as well

**Comment by Gunjanrathore8178** [comment]
Can I do it?

**Comment by boradesanket13** [comment]
Go ahead!
