### ISSUE TITLE
Improve the UI

### ISSUE THREAD

**Issue by AbhishekKumar2002** [boradesanket13/Numericon#93]
Hi @Sanket1308, I will Animate the text and make the website more attractive. Please give this label of Hacktoberfest

**Comment by boradesanket13** [comment]
Make look authentic/simple. 
Go ahead! Contribute well🚀

**Comment by AbhishekKumar2002** [comment]
Will you please add Hacktoberfest label to it

**Comment by AbhishekKumar2002** [comment]
![Screenshot (243)](https://user-images.githubusercontent.com/96721263/195853049-5711270c-a3e9-473f-8069-b25d6448e86a.png)


Here is a basic look of the improved web page. The heading simple calculator has a animation running in it
