### ISSUE TITLE
Change Background images

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/Numericon#95]
Add black and white themed images

**Comment by Omhere** [comment]
I would like to contribute to this pls

**Comment by pranjal0s** [comment]
assign this task to me i would like to contribute

**Comment by boradesanket13** [comment]
@pranjal0s , thanks for your interest!

We're assigning issues on a first come first serve basis. If @Omhere isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue [here](https://github.com/boradesanket13?tab=repositories).

**Comment by ghost** [comment]
@boradesanket13 I would like to contribute to this issue. Please assign it to me.

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀

**Comment by ankushj0801** [comment]
please assign it to me

**Comment by Gaurav945572** [comment]
I would like to contribute please assign me this task

**Comment by NihalAhmadKhan** [comment]
I want to contribute in this project

**Comment by boradesanket13** [comment]
Thanks for your interest!

We're assigning issues on a first come first serve basis. If first assigned person isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another CODEPEAKissue [here](https://github.com/Sanket1308?tab=repositories).
