### ISSUE TITLE
Add linkedIn twitter icons on footer

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/Numericon#97]

**Comment by Harshalia** [comment]
Assign me this pls

**Comment by pranjal0s** [comment]
assign this task to me

**Comment by boradesanket13** [comment]
@pranjal0s , thanks for your interest!

@, we're assigning issues on a first come first serve basis. If @Harshalia isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue [here](https://github.com/Sanket1308?tab=repositories).

**Comment by gizmo50** [comment]
Is this issue opened to be assigned for CodePeak?

**Comment by boradesanket13** [comment]
Yes, @gizmo50 
Go ahead! Contribute well🚀

**Comment by raunak-mishra** [comment]
I'd like to take this up. Kindly assign it

**Comment by ankushj0801** [comment]
Please assign it to me

**Comment by Gaurav945572** [comment]
Please assign it to me.

**Comment by sidling1** [comment]
I'd like to do this

**Comment by iamatifmoin** [comment]
@boradesanket13 
I have resolved the issue. Please review the PR.

**Comment by sankooru14** [comment]
@boradesanket13 
please assign this issue to me

**Comment by Tushar98644** [comment]
If this issue is still open,i would to work on it...

**Comment by iamatifmoin** [comment]
@boradesanket13 
Please review the PR.
