### ISSUE TITLE
Improve Darkmode

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/Numericon#98]

**Comment by Omhere** [comment]
Assign me

**Comment by shivesh1606** [comment]
@boradesanket13  Assign it to me.

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀

**Comment by raunak-mishra** [comment]
@boradesanket13 I'd like to take this up. Kindly assign it

**Comment by Tushar98644** [comment]
@boradesanket13 I would also like to work on it....

**Comment by NihalAhmadKhan** [comment]
I would like to work on this project I have knowledge about this

**Comment by shivesh1606** [comment]
![image](https://user-images.githubusercontent.com/75152702/205874448-eda9c2cc-af2b-42d4-825c-c77c7683331f.png)





@boradesanket13 should I proceed with this design?

**Comment by boradesanket13** [comment]
- Change background image and simple looking images and design @DarK-VEnOM-16

**Comment by AnkitAnandMastery17** [comment]
@boradesanket13 Is this still open? If yes, can you assign it to me?
